##[==[
local utils = require './utils.lua'

linklib(utils.lib)
cinclude(utils.header)
]==]

require './bindings.nelua'

local uws = @record {}
return uws

-- Initialization
local app = require './app.nelua'

function uws.app(options: us_socket_context_options_t): *app
  return uws_create_app(0, options)
end

local uws.request = require './request.nelua'
local uws.response = require './response.nelua'
